likes(ram,sita).
likes(ram,trains).
likes(suresh,fast_cars).
likes(Person1,Person2):-
hobby(Person1,Hobby),
hobby(Person2,Hobby).
hobby(ram,trainspotting).
hobby(saroj,sailing).
hobby(tina,trainspotting).
hobby(prakash,sailing).
